name: SVGScout
options:
  bundleIdPrefix: com.svgscout
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    CLANG_ENABLE_MODULES: YES

targets:
  SVG Scout:
    type: application
    platform: macOS
    sources:
      - path: SVG Scout
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.svgscout.app
        INFOPLIST_FILE: SVG Scout/Info.plist
        CODE_SIGN_ENTITLEMENTS: SVG Scout/SVG Scout.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: SVG Scout Extension
        embed: true
        codeSign: true
        copyPhase:
          destination: plugins

  SVG Scout Extension:
    type: app-extension
    platform: macOS
    sources:
      - path: SVG Scout Extension
        excludes:
          - Resources
          - "**/.DS_Store"
      - path: SVG Scout Extension/Resources
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.svgscout.app.extension
        INFOPLIST_FILE: SVG Scout Extension/Info.plist
        CODE_SIGN_ENTITLEMENTS: SVG Scout Extension/SVG Scout Extension.entitlements
        CODE_SIGN_STYLE: Automatic
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: NO
        SKIP_INSTALL: YES

schemes:
  SVG Scout (macOS):
    build:
      targets:
        SVG Scout: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
